# Generated by Django 5.1.5 on 2025-01-31 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0010_pokemon_next_evolution_pokemon_previous_evolution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='previous_evolution',
        ),
    ]
