# Generated by Django 5.1.5 on 2025-02-04 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0019_alter_pokemon_previous_evolution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='name',
            new_name='pokemon',
        ),
    ]
